// Mock data for PCP SaaS Platform
export const mockData = {
  kpis: {
    totalOrders: 47,
    activeOrders: 12,
    plannedOrders: 18,
    completedOrders: 15,
    cancelledOrders: 2,
    totalProduced: 3840,
    totalRejected: 76,
    totalProducts: 24,
    totalMachines: 8,
    totalPlants: 3,
    completionRate: 68,
    qualityRate: 98,
  },
  plants: [
    { id: 'p1', name: 'Planta Alpha', location: 'São Paulo - SP', totalCapacity: 500, contact: 'Carlos Silva', status: 'active', notes: 'Planta principal de produção' },
    { id: 'p2', name: 'Planta Beta', location: 'Campinas - SP', totalCapacity: 320, contact: 'Ana Souza', status: 'active', notes: 'Especializada em montagem' },
    { id: 'p3', name: 'Planta Gamma', location: 'Santo André - SP', totalCapacity: 180, contact: 'Roberto Lima', status: 'inactive', notes: 'Em manutenção programada' },
  ],
  machines: [
    { id: 'm1', name: 'Torno CNC-01', plantId: 'p1', plantName: 'Planta Alpha', type: 'CNC', capacity: '200 peças/h', status: 'operational', specs: 'Fanuc 0i-MF, 3 eixos' },
    { id: 'm2', name: 'Fresadora CNC-02', plantId: 'p1', plantName: 'Planta Alpha', type: 'Fresadora', capacity: '150 peças/h', status: 'maintenance', specs: 'Siemens 840D' },
    { id: 'm3', name: 'Prensa Hidráulica-01', plantId: 'p2', plantName: 'Planta Beta', type: 'Prensa', capacity: '300 ton', status: 'operational', specs: '300 toneladas, curso 500mm' },
    { id: 'm4', name: 'Robô de Solda-01', plantId: 'p1', plantName: 'Planta Alpha', type: 'Robótica', capacity: '80 cordões/h', status: 'operational', specs: 'KUKA KR 16' },
    { id: 'm5', name: 'Injetora Plástico-01', plantId: 'p2', plantName: 'Planta Beta', type: 'Injetora', capacity: '500 ciclos/h', status: 'offline', specs: '250 ton, 1200g' },
    { id: 'm6', name: 'Centro Usinagem-01', plantId: 'p1', plantName: 'Planta Alpha', type: 'CNC', capacity: '100 peças/h', status: 'operational', specs: 'DMG MORI 5 eixos' },
  ],
  products: [
    { id: 'pr1', name: 'Tampa de Alumínio A200', code: 'TAM-A200', description: 'Tampa de fechamento em alumínio anodizado', unit: 'un' },
    { id: 'pr2', name: 'Eixo Transmissão T500', code: 'EXT-T500', description: 'Eixo de transmissão em aço SAE 1045', unit: 'un' },
    { id: 'pr3', name: 'Suporte Lateral SL100', code: 'SLT-SL100', description: 'Suporte lateral em chapa dobrada', unit: 'un' },
    { id: 'pr4', name: 'Carcaça Motor CM300', code: 'CRC-CM300', description: 'Carcaça do motor em ferro fundido', unit: 'un' },
    { id: 'pr5', name: 'Engrenagem Cônica EC-45', code: 'ENG-EC45', description: 'Engrenagem cônica módulo 3, 45 dentes', unit: 'un' },
    { id: 'pr6', name: 'Pino Elástico PE-12', code: 'PIN-PE12', description: 'Pino elástico DIN 1481, diâm 12mm', unit: 'un' },
  ],
  productionOrders: [
    { id: 'op1', code: 'OP-2024-001', productName: 'Tampa de Alumínio A200', quantity: 500, startDate: '2024-02-01', endDate: '2024-02-10', status: 'completed', priority: 'high', plantName: 'Planta Alpha', completedQuantity: 500 },
    { id: 'op2', code: 'OP-2024-002', productName: 'Eixo Transmissão T500', quantity: 200, startDate: '2024-02-05', endDate: '2024-02-15', status: 'in_progress', priority: 'urgent', plantName: 'Planta Alpha', completedQuantity: 120 },
    { id: 'op3', code: 'OP-2024-003', productName: 'Suporte Lateral SL100', quantity: 350, startDate: '2024-02-10', endDate: '2024-02-20', status: 'in_progress', priority: 'medium', plantName: 'Planta Beta', completedQuantity: 85 },
    { id: 'op4', code: 'OP-2024-004', productName: 'Carcaça Motor CM300', quantity: 100, startDate: '2024-02-12', endDate: '2024-02-25', status: 'planned', priority: 'high', plantName: 'Planta Beta', completedQuantity: 0 },
    { id: 'op5', code: 'OP-2024-005', productName: 'Engrenagem Cônica EC-45', quantity: 800, startDate: '2024-02-15', endDate: '2024-02-28', status: 'planned', priority: 'medium', plantName: 'Planta Alpha', completedQuantity: 0 },
    { id: 'op6', code: 'OP-2024-006', productName: 'Pino Elástico PE-12', quantity: 2000, startDate: '2024-02-01', endDate: '2024-02-08', status: 'completed', priority: 'low', plantName: 'Planta Alpha', completedQuantity: 2000 },
    { id: 'op7', code: 'OP-2024-007', productName: 'Tampa de Alumínio A200', quantity: 300, startDate: '2024-02-18', endDate: '2024-02-25', status: 'planned', priority: 'medium', plantName: 'Planta Alpha', completedQuantity: 0 },
    { id: 'op8', code: 'OP-2024-008', productName: 'Eixo Transmissão T500', quantity: 150, startDate: '2024-02-20', endDate: '2024-02-28', status: 'cancelled', priority: 'low', plantName: 'Planta Beta', completedQuantity: 0 },
  ],
  productionEntries: [
    { id: 'ae1', orderCode: 'OP-2024-002', stepName: 'Torneamento', quantityProduced: 60, quantityRejected: 2, timeSpent: 120, operator: 'João Ferreira', recordedAt: '2024-02-06' },
    { id: 'ae2', orderCode: 'OP-2024-002', stepName: 'Fresamento', quantityProduced: 60, quantityRejected: 1, timeSpent: 90, operator: 'Maria Santos', recordedAt: '2024-02-07' },
    { id: 'ae3', orderCode: 'OP-2024-003', stepName: 'Corte', quantityProduced: 85, quantityRejected: 3, timeSpent: 60, operator: 'Paulo Costa', recordedAt: '2024-02-11' },
    { id: 'ae4', orderCode: 'OP-2024-001', stepName: 'Montagem Final', quantityProduced: 500, quantityRejected: 8, timeSpent: 240, operator: 'Ana Lima', recordedAt: '2024-02-10' },
  ],
  workInstructions: [
    { id: 'wi1', title: 'Procedimento de Torneamento CNC', code: 'IT-CNC-001', version: 3, status: 'published', createdBy: 'Eng. Carlos', approvedBy: 'Gerente Silva', productName: 'Eixo Transmissão T500' },
    { id: 'wi2', title: 'Inspeção Visual de Superfícies', code: 'IT-QUAL-002', version: 1, status: 'approved', createdBy: 'Eng. Ana', approvedBy: 'Gerente Silva', productName: null },
    { id: 'wi3', title: 'Montagem de Carcaça do Motor', code: 'IT-MON-003', version: 2, status: 'review', createdBy: 'Eng. Roberto', approvedBy: null, productName: 'Carcaça Motor CM300' },
    { id: 'wi4', title: 'Solda MIG em Aço Carbono', code: 'IT-SOLD-004', version: 1, status: 'draft', createdBy: 'Eng. Paulo', approvedBy: null, productName: null },
    { id: 'wi5', title: 'Setup de Fresadora 5 Eixos', code: 'IT-CNC-005', version: 2, status: 'published', createdBy: 'Eng. Carlos', approvedBy: 'Gerente Lima', productName: null },
  ],
  bomItems: [
    { id: 'b1', productName: 'Eixo Transmissão T500', productCode: 'EXT-T500', componentName: 'Barra Aço SAE 1045 Ø50', componentCode: 'MAT-001', quantity: 1, unit: 'm' },
    { id: 'b2', productName: 'Eixo Transmissão T500', productCode: 'EXT-T500', componentName: 'Rolamento 6205-2RS', componentCode: 'ROL-001', quantity: 2, unit: 'un' },
    { id: 'b3', productName: 'Eixo Transmissão T500', productCode: 'EXT-T500', componentName: 'Anel de Retenção', componentCode: 'ANL-001', quantity: 2, unit: 'un' },
    { id: 'b4', productName: 'Carcaça Motor CM300', productCode: 'CRC-CM300', componentName: 'Lingote Ferro Fundido GG-25', componentCode: 'MAT-010', quantity: 5, unit: 'kg' },
    { id: 'b5', productName: 'Carcaça Motor CM300', productCode: 'CRC-CM300', componentName: 'Parafuso M8x25', componentCode: 'PAR-001', quantity: 12, unit: 'un' },
    { id: 'b6', productName: 'Tampa de Alumínio A200', productCode: 'TAM-A200', componentName: 'Chapa Al 6061 3mm', componentCode: 'MAT-005', quantity: 0.5, unit: 'kg' },
  ],
  routes: [
    { id: 'r1', productName: 'Eixo Transmissão T500', productCode: 'EXT-T500', name: 'Roteiro Principal', steps: [
      { order: 1, operation: 'Corte da Barra', resourceType: 'machine', standardTime: 15 },
      { order: 2, operation: 'Torneamento Externo', resourceType: 'machine', standardTime: 45 },
      { order: 3, operation: 'Fresamento de Canal', resourceType: 'machine', standardTime: 30 },
      { order: 4, operation: 'Inspeção Dimensional', resourceType: 'workbench', standardTime: 20 },
    ]},
    { id: 'r2', productName: 'Tampa de Alumínio A200', productCode: 'TAM-A200', name: 'Roteiro Estamparia', steps: [
      { order: 1, operation: 'Corte a Laser', resourceType: 'machine', standardTime: 10 },
      { order: 2, operation: 'Estampagem', resourceType: 'machine', standardTime: 25 },
      { order: 3, operation: 'Rebarbação', resourceType: 'workbench', standardTime: 15 },
      { order: 4, operation: 'Anodização', resourceType: 'manual', standardTime: 60 },
    ]},
  ],
  mrpEntries: [
    { id: 'mrp1', productName: 'Eixo Transmissão T500', componentName: 'Barra Aço SAE 1045 Ø50', requiredQuantity: 200, availableQuantity: 80, shortfall: 120, suggestedAction: 'purchase', generatedAt: '2024-02-15' },
    { id: 'mrp2', productName: 'Eixo Transmissão T500', componentName: 'Rolamento 6205-2RS', requiredQuantity: 400, availableQuantity: 250, shortfall: 150, suggestedAction: 'purchase', generatedAt: '2024-02-15' },
    { id: 'mrp3', productName: 'Carcaça Motor CM300', componentName: 'Lingote Ferro Fundido GG-25', requiredQuantity: 500, availableQuantity: 320, shortfall: 180, suggestedAction: 'purchase', generatedAt: '2024-02-15' },
    { id: 'mrp4', productName: 'Tampa de Alumínio A200', componentName: 'Chapa Al 6061 3mm', requiredQuantity: 150, availableQuantity: 200, shortfall: 0, suggestedAction: 'manufacture', generatedAt: '2024-02-15' },
    { id: 'mrp5', productName: 'Engrenagem Cônica EC-45', componentName: 'Bloco Aço 8620', requiredQuantity: 800, availableQuantity: 200, shortfall: 600, suggestedAction: 'purchase', generatedAt: '2024-02-15' },
  ],
  workbenches: [
    { id: 'wb1', name: 'Bancada de Inspeção 01', plantName: 'Planta Alpha', function: 'Inspeção Dimensional', status: 'available' },
    { id: 'wb2', name: 'Bancada de Montagem 01', plantName: 'Planta Alpha', function: 'Montagem de Subconjuntos', status: 'in_use' },
    { id: 'wb3', name: 'Bancada de Solda 01', plantName: 'Planta Beta', function: 'Soldagem Manual', status: 'available' },
    { id: 'wb4', name: 'Bancada de Rebarbação', plantName: 'Planta Alpha', function: 'Acabamento Superficial', status: 'maintenance' },
  ],
  users: [
    { id: 'u1', name: 'Carlos Silva', email: 'carlos@empresa.com', role: 'admin' },
    { id: 'u2', name: 'Ana Souza', email: 'ana@empresa.com', role: 'gestor_pcp' },
    { id: 'u3', name: 'João Ferreira', email: 'joao@empresa.com', role: 'operador' },
    { id: 'u4', name: 'Maria Santos', email: 'maria@empresa.com', role: 'qualidade' },
  ],
  chartData: {
    ordersPerWeek: [8, 12, 9, 15, 11, 14, 12],
    productionPerDay: [320, 480, 390, 520, 410, 550, 490],
    qualityPerWeek: [98.5, 97.2, 98.8, 99.1, 97.8, 98.4, 99.0],
    statusDistribution: { planned: 18, in_progress: 12, completed: 15, cancelled: 2 },
    capacityUtilization: { 'Planta Alpha': 78, 'Planta Beta': 62, 'Planta Gamma': 0 },
  }
};
